artist/urls.py
from django.urls import path
from . import views


app_name = 'artists'

urlpatterns = [
    path('', views.show_artists, name='index'),
    path('<int:artist_id>', views.show_artist, name='by_id'),
    path('<int:artist_id>/creations/<int:creation_id>', views.get_artist_creation, name="by_artist_and_creation_id")
]

sensoson/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('', views.home, name="home"),
    path('artists/', include('artist.urls')),
    path('admin/', admin.site.urls),
]

artist/models.py
from django.db import models
from django.utils import timezone


class Type(models.Model):
    label = models.CharField(max_length=30)

    def __str__(self):
        return "{0} {1}".format(self.id, self.label)


class Artist(models.Model):
    name = models.CharField(max_length=25)
    firstName = models.CharField(max_length=15)
    birthday = models.DateField(default=timezone.now)
    biography = models.TextField(max_length=1000)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "{0} {1} {2} {3} {4}"\
            .format(self.id, self.name, self.firstName, self.birthday, self.biography)


class Creation(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField(
        verbose_name='Creation date',
        default=timezone.now
    )
    place = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    type = models.ForeignKey(Type, null=True, on_delete=models.SET_NULL)
    artist = models.ForeignKey(Artist, null=False, on_delete=models.CASCADE)
    # TODO: Put images

    class Meta:
        ordering = ['date']

    def __str__(self):
        return "{0} {1} {2} {3} {4} {5}"\
            .format(self.id, self.title, self.date, self.place, self.content, self.type)

home/models.py
from django.db import models

# Create your models here.

artist/views.py
from django.shortcuts import render, get_object_or_404
from artist.models import Artist, Creation


def show_artists(request):
    return render(request, 'artists.html', {'artists': Artist.objects.all()})


def show_artist(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)
    return render(request, 'artist.html', {'artist': artist})


def get_artist_creation(request, artist_id, creation_id):
    artist = get_object_or_404(Artist, id=artist_id)
    creation = get_object_or_404(Creation, id=creation_id)
    return render(request, 'creation.html', {'artist': artist, 'creation': creation})

home/views.py
from django.shortcuts import render
from artist.models import Artist


def home(request):
    return render(request, 'home.html', {'artists': Artist.objects.all()})

artist/templates/artist.html
{% extends "base.html" %}

{% block title %} {{ artist.name }} {{ artist.firstName }} {% endblock %}

{% block nav %}
    <nav>
        Birthday : {{ artist.birthday }} <br/>
        Biography :
        <pre>{{ artist.biography }}</pre>
        <br/>

        <ul>
            {% for creation in artist.creation_set.all %}
                <li>
                    <a href="{% url 'artists:by_artist_and_creation_id' artist_id=artist.id creation_id=creation.id %}"> {{ creation.title }} </a>
                </li>
            {% endfor %}
        </ul>

        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
        </ul>
    </nav>
{% endblock %}

{% block content %}

    {% for creation in artist.creation_set.all %}
        <article>
            <div class="creation">
                <h3>{{ creation.title }}</h3>
                <p>{{ creation.content|truncatewords_html:80 }}</p>
                <p><a href="{% url 'artists:by_artist_and_creation_id' artist_id=artist.id creation_id=creation.id %}">
                    Lire la suite </a></p>
            </div>
        </article>
    {% endfor %}

{% endblock %}

artist/templates/artists.html
{% extends "home.html" %}

{% block title %} Artists {% endblock %}

{% block nav %}
{{ block.super }}
{% endblock %}

{% block content %}

    {% for artist in artists %}
        <article>
            Name : {{ artist.name }} {{ artist.firstName }} <br/>
            Birthday : {{ artist.birthday }} <br/>
            Biography : <br/>
            <pre>
        {{ artist.biography }}
    </pre>

            <ul>
                {% for creation in artist.creation_set.all %}
                    <li>{{ creation.title }}</li>
                {% endfor %}
            </ul>
        </article>

    {% empty %}
        No artist
    {% endfor %}

{% endblock %}

artist/templates/creation.html
{% extends "artist.html" %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block nav %}
{{ block.super }}
{% endblock %}

{% block content %}

    <h2>{{ creation.title }}</h2>
    <i>réalisé le : {{ creation.date }} à {{ creation.place }}</i><br />

    {{ creation.content }}

{% endblock %}

home/templates/home.html
{% extends "base.html" %}
{% block title %} Hello World ! {% endblock %}
{% block nav %}
    <nav>
        Summary :
        <ul>
            <li><a href="{% url 'artists:index' %}">Artistes</a></li>
            <ul>
                {% for artist in artists %}
                    <li><a href="{% url 'artists:by_id' artist_id=artist.id %}"> {{ artist.name }}</a></li>
                {% endfor %}
            </ul>
            <li><a href="{% url 'home' %}" >Home</a></li>
        </ul>
    </nav>
{% endblock nav %}
{% block content %}
    <article>
        <h2>Welcome on our home page. </h2>
    </article>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>SensÔson</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Style the header */
        header {
            background-color: #7f7eff;
            padding: 30px;
            text-align: center;
            font-size: 35px;
            color: white;
        }

        /* Create two columns/boxes that floats next to each other */
        nav {
            float: left;
            width: 30%;
            height: 300px; /* only for demonstration, should be removed */
            background: #a390e4;
            padding-top: 20px;
            padding-left: 20px;
            padding-right: 20px;
        }

        article {
            float: left;
            padding: 20px;
            width: 70%;
            background-color: #c69dd2;
            height: 300px; /* only for demonstration, should be removed */
        }

        /* Clear floats after the columns */
        section:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Style the footer */
        footer {
            background-color: #c68866;
            padding: 20px;
            text-align: center;
            color: white;
        }

        /* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
        @media (max-width: 600px) {
            nav, article {
                width: 100%;
                height: auto;
            }
        }
    </style>
</head>
<body>
<header>
    <h1>
        {% block title %}{% endblock %}
    </h1>
</header>

<nav>
    {% block nav %}{% endblock %}
</nav>

<section>
    {% block content %}{% endblock %}
</section>

<footer>
    CopyLeft
</footer>
</body>
</html>